import { getService } from '@universal-ember/test-support';
import { module, test } from 'qunit';

import { baseRealm } from '@cardstack/runtime-common';
import type { Loader } from '@cardstack/runtime-common/loader';

import ListingCreateCommand from '@cardstack/host/commands/listing-create';

import type { Spec } from 'https://cardstack.com/base/spec';

import {
  testRealmURL,
  setupCardLogs,
  setupIntegrationTestRealm,
  setupLocalIndexing,
  setupAuthEndpoints,
  setupRealmServerEndpoints,
  setupRealmCacheTeardown,
  withCachedRealmSetup,
} from '../../helpers';
import { setupBaseRealm, CardDef } from '../../helpers/base-realm';
import { setupMockMatrix } from '../../helpers/mock-matrix';
import { setupRenderingTest } from '../../helpers/setup';

module(
  'Integration | Command | listing-create | linkSpecs',
  function (hooks) {
    setupRenderingTest(hooks);
    setupBaseRealm(hooks);
    let loader: Loader;

    // Provide proxy endpoint stubs for AI-based calls (readme generation, etc.)
    setupRealmServerEndpoints(hooks, [
      {
        route: '_request-forward',
        getResponse: async (req: Request) => {
          const body = await req.json();
          if (body.url === 'https://openrouter.ai/api/v1/chat/completions') {
            return new Response(
              JSON.stringify({
                choices: [
                  {
                    message: {
                      content: '# Stub README\n\nGenerated by test stub.',
                    },
                  },
                ],
              }),
              {
                status: 200,
                headers: { 'Content-Type': 'application/json' },
              },
            );
          }
          return new Response(JSON.stringify({ error: 'Unknown endpoint' }), {
            status: 404,
            headers: { 'Content-Type': 'application/json' },
          });
        },
      },
    ]);

    setupLocalIndexing(hooks);
    let mockMatrixUtils = setupMockMatrix(hooks, {
      loggedInAs: '@testuser:localhost',
      activeRealms: [testRealmURL],
      autostart: true,
    });
    setupCardLogs(
      hooks,
      async () => await loader.import(`${baseRealm.url}card-api`),
    );
    setupRealmCacheTeardown(hooks);

    hooks.beforeEach(function () {
      loader = getService('loader-service').loader;
    });

    hooks.beforeEach(async function () {
      setupAuthEndpoints();
      await withCachedRealmSetup(async () =>
        setupIntegrationTestRealm({
          mockMatrixUtils,
          realmURL: testRealmURL,
          contents: {
            'pet.gts': `
              import { CardDef, field, contains } from 'https://cardstack.com/base/card-api';
              import StringField from 'https://cardstack.com/base/string';

              export class Pet extends CardDef {
                static displayName = 'Pet';
                @field name = contains(StringField);
              }
            `,
            '.realm.json': `{ "name": "Link Specs Test Realm" }`,
          },
        }),
      );
    });

    test('linkSpecs creates a spec for the module itself (not just its dependencies)', async function (assert) {
      let commandService = getService('command-service');
      let command = new ListingCreateCommand(commandService.commandContext);

      // Create a minimal listing-like object to pass to linkSpecs
      let listing = new CardDef() as any;

      let moduleUrl = `${testRealmURL}pet.gts`;

      // Call linkSpecs directly (private method, accessed via bracket notation)
      let specs: Spec[] = await (command as any).linkSpecs(
        listing,
        testRealmURL,
        moduleUrl, // resourceUrl — same as moduleUrl when no openCardId
        moduleUrl, // moduleUrl — the module of the card type being listed
      );

      assert.ok(Array.isArray(specs), 'returns an array of specs');
      assert.ok(specs.length > 0, 'at least one spec was created');

      let specModules = specs.map((s: Spec) => s.ref?.module);
      assert.ok(
        specModules.some(
          (m: string | undefined) =>
            m === moduleUrl || m === moduleUrl.replace(/\.gts$/, ''),
        ),
        `specs include one for the module itself (${moduleUrl}), found: ${specModules.join(', ')}`,
      );
    });

    test('linkSpecs assigns specs to listing', async function (assert) {
      let commandService = getService('command-service');
      let command = new ListingCreateCommand(commandService.commandContext);

      let listing = new CardDef() as any;
      let moduleUrl = `${testRealmURL}pet.gts`;

      await (command as any).linkSpecs(
        listing,
        testRealmURL,
        moduleUrl,
        moduleUrl,
      );

      assert.ok(
        Array.isArray(listing.specs),
        'listing.specs was assigned an array',
      );
      assert.ok(listing.specs.length > 0, 'listing.specs is not empty');
    });
  },
);
